name: Deploy OSRS App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: "157.230.53.158"
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/wiseoldtools/osrs-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart osrs-app
            systemctl restart osrs-scanner
            echo "🚀 Successfully deployed to wiseoldtools.com!"